Isuue #2908496 Paragraphs paste feature
thunder/thunder-distribution pull request #104
Opened 2019-11-25 11:37 UTC by ol0lll

Make sure these boxes are checked before submitting your pull request - thank you!

- [ ] All coding styles are fulfilled. ([How to check for cs issues?](https://github.com/BurdaMagazinOrg/thunder-dev-tools/blob/master/README.md#code-style-guidelines))
- [ ] All tests are running locally. ([How to run the test?](https://github.com/thunder/thunder-distribution/blob/8.x-3.x/docs/development.md#how-to-run-the-tests))
- [ ] Necessary update hooks are provided.
- [ ] User roles have correct access for new introduced permission.
- [ ] Every thunder module has a README.md in its root. Follow [this guidelines](https://www.drupal.org/node/2181737), but we don't need every topic.
- [ ] Code is covered with well-balanced amount of inline comments.

If you are really awesome, then your feature is covered by additional tests. Well done!

2019-11-25 14:08 UTC, ol0lll commented
`With the launch of the new CMS, Burda is creating a worldwide coalition for publishers, industry partners, and developers. At the core of the community is a team of publishing experts and developers led by Ingo Rübe, CTO for Burda’s German publishing operations, and initiator of Thunder.

https://youtube.com/watch?v=v9VlleQPW2A&index=3&list=PL7xqy2B8uXNI-uKDix02rQRIgy9Y_lM6-

https://vimeo.com/31560992

This team will also be responsible for coordinating the continuous development and enhancement of Thunder. Ingo Rübe explains,“A CMS is no longer a strategic differentiator, especially in the consumer’s perception.

https://www.instagram.com/p/2rh_YmDglx/

Board Member Philipp Welte explains, “Success in this new era of publishing can only be achieved by keeping up with the lightning speed of technological progress."

https://twitter.com/rteijeiro/status/719814039241625600`

2019-11-28 08:31 UTC, dbosen requested changes

2019-11-28 08:31 UTC, dbosen commented on modules/paragraphs_paste/js/paragraphs-paste.js
> +    pastedData = JSON.stringify(clipboardData.getData('Text').split(/\n\s?\n/));
1) This will be problematic with windows users.
2) We should rethink the split approach. I would suggest, that we do an additional split after splitting on linebreaks.
In the split text, we could also split before and after known embed-urls. For example:

``` text, text more text and some other text https://twitter.com/kanyewest/status/1196524372044861440   and now even more fine information for the reader```

would be split to 
` text, text more text and some other text `
and
`https://twitter.com/kanyewest/status/1196524372044861440` 
and
`and now even more fine information for the reader` 

Since we would have to recognize "known" URLs for this, we will probably do this on the server-side.

2019-12-11 09:23 UTC, ol0lll commented on modules/paragraphs_paste/js/paragraphs-paste.js
> +    pastedData = JSON.stringify(clipboardData.getData('Text').split(/\n\s?\n/));
@klucic Should we split on embed urls inside a text block? What do you think?

2022-01-17 15:43 UTC, dbosen requested changes
We need to add at least some basic documentation here. Similar to the "About text format" Tips page for the CKEditor.

2022-01-17 15:47 UTC, dbosen commented
In general I think we are getting closer! The usage is still a bit awkward, with the text staying in the field after submission. 
Volkers idea with an overlay instead might be worth thinking about.

Clicking on the "create paragraphs" button would open the overlay with the textfield. Then clicking on Submit or create in the overlay closes the overlay and adds the paragraphs, the focus of the page scrolls to the first created paragraph.

2022-04-06 09:41 UTC, chrfritsch requested changes

2022-04-06 09:41 UTC, chrfritsch commented on modules/thunder_paragraphs_paste/thunder_paragraphs_paste.install
> +        'text' => 'paragraph.text.field_text',
Needs an update

2022-04-11 14:46 UTC, dbosen submitted a review, later dismissed
I think, we have it now

2022-04-12 07:17 UTC, chrfritsch commented on composer.json
> +        "drupal/paragraphs_paste": "dev-2.x",
We need a tagged version

2022-04-12 13:52 UTC, chrfritsch approved these changes

2022-04-12 14:33 UTC, merged