Issue #2899254: Integrate editorial search with Search API module (4.x)
thunder/thunder-distribution pull request #152
Opened 2020-02-04 11:49 UTC by mtodor

2020-04-03 06:59 UTC, chrfritsch requested changes

2020-04-03 06:59 UTC, chrfritsch commented on composer.json
> +        "drupal/views_bulk_operations": "^2.4",
views_bulk_operations 3 is already out and recommended

2020-04-03 06:59 UTC, chrfritsch commented on composer.json
> +                "Reset-tracker drush command functionality is misleading": "https://www.drupal.org/files/issues/2020-03-12/3119335.patch"
Patch needs adjustment

2020-07-06 12:37 UTC, dbosen commented
We should add search to media tab and media browser(?)

2020-07-06 12:42 UTC, dbosen commented
We need better test coverage for this.

2020-07-06 14:42 UTC, dbosen requested changes

2020-07-06 14:42 UTC, dbosen commented on .github/workflows/test.yml
> -    needs: [build, test-max]
Lets not forget to put that back

2020-07-06 14:42 UTC, dbosen commented on composer.json
> +        "drupal/facets": "1.x-dev",
-dev? Oh boy... I guess, we need to change this to @dev now, that we have stability alpha

2020-08-27 10:33 UTC, closed without merging