Add upgrade testing
thunder/thunder-distribution pull request #16
Opened 2019-05-27 10:53 UTC by chrfritsch

Make sure these boxes are checked before submitting your pull request - thank you!

- [ ] All coding styles are fulfilled. ([How to check for cs issues?](https://github.com/BurdaMagazinOrg/thunder-dev-tools/blob/master/README.md#code-style-guidelines))
- [ ] All tests are running locally. ([How to run the test?](https://github.com/thunder/thunder-distribution/blob/8.x-3.x/docs/development.md#how-to-run-the-tests))
- [ ] Necessary update hooks are provided.
- [ ] User roles have correct access for new introduced permission.
- [ ] Every thunder module has a README.md in its root. Follow [this guidelines](https://www.drupal.org/node/2181737), but we don't need every topic.
- [ ] Code is covered with well-balanced amount of inline comments.

If you are really awesome, then your feature is covered by additional tests. Well done!

2019-06-06 07:55 UTC, chrfritsch commented
This is the current status:
The upgrade from Thunder 2 (prefer-lowest) to Thunder 2 (latest) works fine. To install Thunder 2 (prefer-lowest) I use a pre-generated composer.lock file, because we did not care about what are the minimum required versions in Thunder 2, so an installation with prefer-lowest would install a Thunder that is not usable. It's also much faster because composer update --prefer-lowest is really slow.

The composer update from T2-T3 also works smoothly, but the db update don't.
For some reason, the state of the ConfigFactory is wrong in some cases. Sadly enough, I was not able to reproduce this with plain Drupal + media_entity + media_entity_image. My latest patch in https://www.drupal.org/project/media_entity/issues/2948704 fixes it partly. But that is just a workaround. There must be a bigger underlying problem.

We still get warnings in watchdog like "A non-existent config entity name returned by FieldStorageConfigInterface::getBundles(): entity type: media, bundle: video, field name: field_author"
That is the reason why currently all tests are failing and it seems to be highly related to the broken ConfigFactory state.

2019-06-06 09:47 UTC, chrfritsch commented
So I found out that config_selector is the root cause. I opened an issue and a failing patch. https://www.drupal.org/project/config_selector/issues/3059870

2019-06-18 11:21 UTC, dbosen requested changes

2019-06-18 11:21 UTC, dbosen commented on scripts/travis/05-update-2-3.sh
> +COMPOSER_MEMORY_LIMIT=-1 composer require "drupal/media_entity:2.x-dev" "drupal/video_embed_field:^2.0" "drupal/media_entity_image" "drupal/riddle_marketplace:^3.0-beta2"
We should put COMPOSER_MEMORY_LIMIT as a global definition into 01-setup-environment.sh

2019-06-18 13:04 UTC, dbosen approved these changes

2019-06-18 14:12 UTC, merged