Issue #3057538: Update to blazy 2.x and slick 2.x
thunder/thunder-distribution pull request #29
Opened 2019-06-19 09:57 UTC by chrfritsch

Make sure these boxes are checked before submitting your pull request - thank you!

- [ ] All coding styles are fulfilled. ([How to check for cs issues?](https://github.com/BurdaMagazinOrg/thunder-dev-tools/blob/master/README.md#code-style-guidelines))
- [ ] All tests are running locally. ([How to run the test?](https://github.com/thunder/thunder-distribution/blob/8.x-3.x/docs/development.md#how-to-run-the-tests))
- [ ] Necessary update hooks are provided.
- [ ] User roles have correct access for new introduced permission.
- [ ] Every thunder module has a README.md in its root. Follow [this guidelines](https://www.drupal.org/node/2181737), but we don't need every topic.
- [ ] Code is covered with well-balanced amount of inline comments.

If you are really awesome, then your feature is covered by additional tests. Well done!

2019-06-19 13:32 UTC, chrfritsch commented
This patch is needed https://www.drupal.org/project/drupal/issues/2863986

2019-06-27 11:51 UTC, dbosen requested changes

2019-06-27 11:51 UTC, dbosen commented on composer.json
> +            },
Add strict core version require.

2019-06-27 11:51 UTC, dbosen commented on drupal-org.make
> +projects[slick][version] = 2
core patch is missing in make file

2019-06-28 12:57 UTC, chrfritsch commented
Hopefully, we can remove the patch with Drupal 8.7.5

2019-07-01 12:27 UTC, dbosen approved these changes

2019-07-01 12:29 UTC, merged