Issue #3065999: Update entity_browser to 8.x-2.2
thunder/thunder-distribution pull request #38
Opened 2019-07-05 08:01 UTC by ol0lll

…llbar

Make sure these boxes are checked before submitting your pull request - thank you!

- [ ] All coding styles are fulfilled. ([How to check for cs issues?](https://github.com/BurdaMagazinOrg/thunder-dev-tools/blob/master/README.md#code-style-guidelines))
- [ ] All tests are running locally. ([How to run the test?](https://github.com/thunder/thunder-distribution/blob/8.x-3.x/docs/development.md#how-to-run-the-tests))
- [ ] Necessary update hooks are provided.
- [ ] User roles have correct access for new introduced permission.
- [ ] Every thunder module has a README.md in its root. Follow [this guidelines](https://www.drupal.org/node/2181737), but we don't need every topic.
- [ ] Code is covered with well-balanced amount of inline comments.

If you are really awesome, then your feature is covered by additional tests. Well done!

2019-07-09 13:16 UTC, mtodor requested changes
I found few problems with EB 2.2.

How to reproduce:

1. New gallery
- create new gallery
- select few images in entity browser
- after entity browser is closed, click on select images again
=> selection will be lost

2. Existing gallery
- click on delete button to remove image from gallery
=> instead of removing image it will open entity browser
(maybe you have to click on two images to reproduce it)

2019-08-29 12:24 UTC, ol0lll commented
> I found few problems with EB 2.2.
Same with EB 1.8

2019-10-01 07:29 UTC, mtodor commented
I have tested this and it looks good.

2019-10-02 08:01 UTC, mtodor approved these changes

2019-10-02 08:02 UTC, merged