Add mappable conditions
thunder/thunder-distribution pull request #520
Opened 2022-02-17 16:16 UTC by dbosen

Make sure these boxes are checked before submitting your pull request - thank you!

- [ ] All coding styles are fulfilled. ([How to check for cs issues?](https://github.com/BurdaMagazinOrg/thunder-dev-tools/blob/master/README.md#code-style-guidelines))
- [ ] All tests are running locally. ([How to run the test?](https://github.com/thunder/thunder-distribution/blob/8.x-4.x/docs/development.md#how-to-run-the-tests))
- [ ] Necessary update hooks are provided.
- [ ] User roles have correct access for new introduced permission.
- [ ] Every thunder module has a README.md in its root. Follow [this guidelines](https://www.drupal.org/node/2181737), but we don't need every topic.
- [ ] Code is covered with well-balanced amount of inline comments.
- [ ] New features or changes are documented.

If you are really awesome, then your feature is covered by additional tests. Well done!

2022-02-21 16:42 UTC, chrfritsch requested changes

2022-02-21 16:42 UTC, chrfritsch commented on modules/thunder_gqls/src/Plugin/GraphQL/DataProducer/EntitiesWithTerm.php
> + *       multiple = FALSE,
Shouldn't this be TRUE?

2022-02-21 16:42 UTC, chrfritsch commented on modules/thunder_gqls/tests/src/Kernel/DataProducer/EntitiesWithTermTest.php
> +  }
Nice tests :)
Could we also have a test with two conditions? Just in case ;)

2022-02-21 16:48 UTC, dbosen commented on modules/thunder_gqls/src/Plugin/GraphQL/DataProducer/EntitiesWithTerm.php
> + *       multiple = FALSE,
Äh...

2022-02-22 09:11 UTC, chrfritsch commented on modules/thunder_gqls/src/Plugin/GraphQL/DataProducer/EntitiesWithTerm.php
> +  public function resolve(TermInterface $term, string $type, array $bundles, string $field, int $offset, int $limit, array $conditions, array $languages, array $sortBy, int $depth, FieldContext $cach
Interface here, too?

2022-02-22 09:12 UTC, dbosen commented on modules/thunder_gqls/src/Plugin/GraphQL/DataProducer/EntitiesWithTerm.php
> +  public function resolve(TermInterface $term, string $type, array $bundles, string $field, int $offset, int $limit, array $conditions, array $languages, array $sortBy, int $depth, FieldContext $cach
Yes, that was actually the plan :-)

2022-02-22 12:12 UTC, chrfritsch approved these changes

2022-02-22 12:28 UTC, merged