Use Drupal 10.3.x
thunder/thunder-distribution pull request #796
Opened 2024-05-07 14:25 UTC by alexpott

Make sure these boxes are checked before submitting your pull request - thank you!

- [ ] All coding styles are fulfilled. ([How to check for cs issues?](https://github.com/BurdaMagazinOrg/thunder-dev-tools/blob/master/README.md#code-style-guidelines))
- [ ] All tests are running locally. ([How to run the test?](https://github.com/thunder/thunder-distribution/blob/8.x-4.x/docs/development.md#how-to-run-the-tests))
- [ ] Necessary update hooks are provided.
- [ ] User roles have correct access for new introduced permission.
- [ ] Every thunder module has a README.md in its root. Follow [this guidelines](https://www.drupal.org/node/2181737), but we don't need every topic.
- [ ] Code is covered with well-balanced amount of inline comments.
- [ ] New features or changes are documented.

If you are really awesome, then your feature is covered by additional tests. Well done!

2024-05-15 07:34 UTC, dbosen requested changes

2024-05-15 07:34 UTC, dbosen commented on .github/workflows/test.yml
> +  DRUPAL_TESTING_VERSION: "dev-TASK-add-upgrade-commands"
I created a new drupal testing: 1.0.42

2024-05-15 08:04 UTC, alexpott commented on .github/workflows/test.yml
> +  DRUPAL_TESTING_VERSION: "dev-TASK-add-upgrade-commands"
❤️

2024-06-17 11:50 UTC, dbosen approved these changes

2024-06-17 11:51 UTC, merged